# https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idcontainer
name: Build pipeline

on:
  push:
  pull_request:
    types: [opened]

jobs:
  unity-pipeline:
    runs-on: ubuntu-latest
    container:
      image: decentraland/renderer-build:2019.4
      env:
        BUILD_TARGET: WebGL
        PROJECT_PATH: ${{ github.workspace }}/unity-client
        BUILD_PATH: ${{ github.workspace }}/unity-client/Builds/unity
        BUILD_NAME: unity
    steps:
      - name: update git
        run: |
          add-apt-repository ppa:git-core/ppa
          apt-get update
          apt-get install -y git git-lfs
          git lfs install

      - name: checkout with LFS
        uses: actions/checkout@v2
        with:
          lfs: true

      # Setup license
      - name: Setup uniy license
        run: sh .github/workflows/scripts/setup-unity.sh

      # Run Editor tests
      - name: Run Editor tests
        run: sh .github/workflows/scripts/run-unity-edit-mode-tests.sh

      # Run PlayMode tests
      - name: Run PlayMode tests
        run: sh .github/workflows/scripts/run-unity-play-mode-tests.sh

      # Build
      - name: Build
        run: sh .github/workflows/scripts/run-unity-build.sh
